abook/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('book.urls'), name='book')
]

book/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
app_name = 'book'
urlpatterns = [
    path('', views.home, name='home'),
    path('create-book/', views.create_book, name='create-book'),
    path('delete_book/<int:pk>', views.delete_book, name='delete_book'),
    path('edit_book/<int:pk>', views.edit_book, name='edit_book'),
    path('see_book/<int:pk>', views.see_book, name='see_book'),



    path('authors/', views.authors, name='authors'),
    path('create-author/', views.create_author, name='create-author'),
    path('delete_author/<int:pk>', views.delete_author, name='delete_author'),
    path('edit_author/<int:pk>', views.edit_author, name='edit_author'),
    path('see_author/<int:pk>', views.see_author, name='see_author'),
]

book/models.py
from django.db import models
# Create your models here.[]


class Author(models.Model):
    name = models.CharField(max_length=30)
    surname = models.CharField(max_length=30)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    birthday = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = "Author"
        ordering = ["-created_at"]


class Book(models.Model):
    title = models.CharField(max_length=25)
    description = models.TextField(blank=True, null=True)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        db_table = "Book"
        ordering = ["-created_at"]

book/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponse
from .models import Author, Book
from datetime import datetime
# Create your views here.
def home(request):
    books = Book.objects.all()
    return render(request, 'book/home.html', {'books':books})

def delete_book(request, pk):
    if pk:
        book = Book.objects.get(id = pk)
        book.delete()
    return redirect(reverse('book:home'))

def edit_book(request, pk):
    if request.method == 'POST':
        if pk:
            book = Book.objects.get(id = pk)
            name = request.POST.get('name')
            if name: book.name = name
            description = request.POST.get('description')
            if description: book.description = description
            author_id = request.POST.get('author_id')
            author = None
            if author_id:
                author = Author.objects.get(id = author_id)
            book.title = name
            book.description = description
            book.author = author
            book.save()
        return redirect(reverse('book:home'))
    authors = Author.objects.all()
    book = Book.objects.get(id = pk)
    return render(request, 'book/edit_book.html', {'book':book, 'authors': authors})

def see_book(request, pk):
    book = Book.objects.get(id = pk)
    return render(request, 'book/see_book.html', {'book':book})

def create_book(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        description = request.POST.get('description')
        id = request.POST.get('author_id')
        if id:
            author = Author.objects.get(id = id)
        else:
            author = None
        Book.objects.create(title = name, description = description, author = author)
        return redirect(reverse('book:home'))
    authors = Author.objects.all()
    return render(request, 'book/create_book.html', {'authors': authors})





def authors(request):
    authors = Author.objects.all()
    books = Book.objects.all()
    return render(request, 'book/authors.html', {'authors':authors, 'books':books})
def delete_author(request, pk):
    if pk:
        author = Author.objects.get(id = pk)
        author.delete()
    return redirect(reverse('book:authors'))

def edit_author(request, pk):
    if request.method == 'POST':
        if pk:
            author = Author.objects.get(id = pk)
            name = request.POST.get('name')
            if name: author.name = name
            surname = request.POST.get('surname')
            if surname: author.surname = surname
            birthday = request.POST.get('birthday')
            birthday = datetime.strptime(birthday, "%Y-%m-%dT%H:%M").strftime("%Y-%m-%d")
            author.name = name
            author.surname = surname
            author.birthday = birthday
            author.save()
        return redirect(reverse('book:authors'))
    author = Author.objects.get(id = pk)
    author.birthday = author.birthday.strftime("%Y-%m-%dT%H:%M")
    return render(request, 'book/edit_author.html', {'author':author})

def see_author(request, pk):
    books = Book.objects.all()
    author = Author.objects.get(id = pk)
    return render(request, 'book/see_author.html', {'author':author, 'books':books})

def create_author(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        surname = request.POST.get('surname')
        birthday = request.POST.get('birthday')
        birthday = datetime.strptime(birthday, "%Y-%m-%dT%H:%M").strftime("%Y-%m-%d")
        Author.objects.create(name = name, surname = surname, birthday = birthday)
        return redirect(reverse('book:authors'))
    return render(request, 'book/create_author.html')

book/templates/book/authors.html
{% extends 'book/base.html' %}
{% block title %} Authors {% endblock %}



{% block body %}
    <b><h1>Authors:</h1></b>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">id</th>
            <th scope="col">Name</th>
            <th scope="col">Surname</th>
            <th scope="col">Birthday</th>
            <th scope="col">Books</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for author in authors %}
        <tr>
            <th scope="row">{{author.id}}</th>
            <td>{{author.name}}</td>
            <td>{{author.surname}}</td>
            <td>{{author.birthday}}</td>
            <td>
                {% for book in books %}
                    {% if book.author == author %}
                        {{book.title}}
                    {% endif %}
                {% endfor %}
            </td>
            <td>
                <a href="{% url 'book:delete_author' author.id %}" style="text-decoration: none; color: white;"><button class="btn btn-danger">Delete</button></a>
                <a href="{% url 'book:edit_author' author.id %}" style="text-decoration: none; color: white;"><button class="btn btn-warning">Edit</button></a>
                <a href="{% url 'book:see_author' author.id %}" style="text-decoration: none; color: white;"><button class="btn btn-primary">See</button></a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="navbar" style="margin: 3vh;">
        <a href="{% url 'book:create-author' %}" style="text-decoration: none; color: white;"><button class="btn btn-success">Create Author</button></a>
    </div>
{% endblock %}

book/templates/book/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>{% block title %} Title {% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'book:home' %}">MySite</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'book:home' %}">Books</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'book:authors' %}">Authors</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    {% block body %}

    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

book/templates/book/create_author.html
{% extends 'book/base.html' %}
{% block title %} Create Book {% endblock %}

{% block body %}

<form action="{% url 'book:create-author' %}" method="post" style="margin: 40px;">
    {% csrf_token %}
    <p>
        <b>Name:</b>
        <input type="text" placeholder="Author's name..." name="name">
    </p>
    <p>
        <b>Surname:</b>
        <input type="text" placeholder="Author surname..." name="surname">
    </p>
    <p>
        <b>Birthday:</b>
        <input type="datetime-local" name="birthday">
    </p>
    <p>
        <input type="button" class="btn btn-success" onclick="this.form.submit()" value="Create">
    </p>
</form>

{% endblock %}

book/templates/book/create_book.html
{% extends 'book/base.html' %}
{% block title %} Create Book {% endblock %}

{% block body %}

<form action="{% url 'book:create-book' %}" method="post" style="margin: 40px;">
    {% csrf_token %}
    <p>
        <b>Kitob nomi:</b>
        <input type="text" placeholder="Kitob nomi..." name="name">
    </p>
    
    <p>
        <b>Izohi nomi:</b>
        <input type="text" placeholder="Izohni kiriting..." name="description">
    </p>
    <p>
        <b>Author nomi:</b>
        <select name="author_id" id="">
            <option value="">__</option>
            {% for author in authors %}
                <option value="{{author.id}}">{{author.name}}</option>
            {% endfor %}
        </select>
    </p>
    <p>
        <input type="button" class="btn btn-success" onclick="this.form.submit()" value="Create">
    </p>
</form>

{% endblock %}

book/templates/book/edit_author.html
{% extends 'book/base.html' %}
{% block title %} Edit Author {% endblock %}


{% block body %}

<form action="{% url 'book:edit_author' author.id %}" method="post" style="margin: 40px;">
    {% csrf_token %}
    <p>
        <b>Name:</b>
        <input type="name" value="{{author.name}}" name="name">
    </p>
    <p>
        <b>Surname:</b>
        <textarea name="surname" id="">{{author.surname}}</textarea>
    </p>
    <p>
        <b>Birthday:</b>
        <input type="datetime-local" value="{{author.birthday}}" name="birthday">
    </p>
    <p>
        <input type="button" class="btn btn-warning" onclick="this.form.submit()" value="Edit">
    </p>
</form>

{% endblock %}

book/templates/book/edit_book.html
{% extends 'book/base.html' %}
{% block title %} Home {% endblock %}


{% block body %}

<form action="{% url 'book:edit_book' book.id %}" method="post" style="margin: 40px;">
    {% csrf_token %}
    <p>
        <b>Name:</b>
        <input type="text" value="{{book.title}}" name="name">
    </p>
    
    <p>
        <b>Description:</b>
        <textarea name="description" id="">{{book.description}}</textarea>
    </p>
    <p>
        <b>Authors:</b>
        <select name="author_id" id="">
            <option value="{{book.author.id}}">{{book.author}}</option>
            {% for author in authors %}
                <option value="{{author.id}}">{{author.name}}</option>
            {% endfor %}
        </select>
    </p>
    <p>
        <input type="button" class="btn btn-warning" onclick="this.form.submit()" value="Edit">
    </p>
</form>

{% endblock %}

book/templates/book/home.html
{% extends 'book/base.html' %}
{% block title %} Home {% endblock %}



{% block body %}
    <b><h1>Books:</h1></b>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Desciption</th>
            <th scope="col">Author</th>
            <th scope="col">Action</th>
        </tr>
        </thead>
        <tbody>
        {% for book in books %}
        <tr>
            <th scope="row">{{book.id}}</th>
            <td>{{book.title}}</td>
            <td>{{book.description}}</td>
            <td>{{book.author}}</td>
            <td>
                <a href="{% url 'book:delete_book' book.id %}" style="text-decoration: none; color: white;"><button class="btn btn-danger">Delete</button></a>
                <a href="{% url 'book:edit_book' book.id %}" style="text-decoration: none; color: white;"><button class="btn btn-warning">Edit</button></a>
                <a href="{% url 'book:see_book' book.id %}" style="text-decoration: none; color: white;"><button class="btn btn-primary">See</button></a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="navbar" style="margin: 3vh;">
        <a href="{% url 'book:create-book' %}" style="text-decoration: none; color: white;"><button class="btn btn-success">Create Book</button></a>
    </div>
{% endblock %}

book/templates/book/see_author.html
{% extends 'book/base.html' %}
{% block title %} See Author {% endblock %}


{% block body %}

<form action="" method="post" style="margin: 40px;">
    {% csrf_token %}
    <p>Name:<b style="margin-left: 1vh;">{{author.name}}</b></p>
    <p>Surname:<b style="margin-left: 1vh;">{{author.surname}}</b></p>
    <p>Birthday:<b style="margin-left: 1vh;">{{author.birthday}}</b></p>
    <p>Books:
        <b style="margin-left: 1vh;">
            {% for book in books %}
                {% if book.author == author %}
                    {{book.title}}
                {% endif %}
            {% endfor %}
        </b>
    </p>
</form>

{% endblock %}

book/templates/book/see_book.html
{% extends 'book/base.html' %}
{% block title %} Home {% endblock %}


{% block body %}

<form action="" method="post" style="margin: 40px;">
    {% csrf_token %}
    <p>Name:<b style="margin-left: 1vh;">{{book.title}}</b></p>
    <p>Description:<b style="margin-left: 1vh;">{{book.description}}</b></p>
    <p>Author:<b style="margin-left: 1vh;">{{book.author}}</b></p>
</form>

{% endblock %}